// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/budgets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/budgets.get').default>>>>
    }
    '/api/categories': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories').default>>>>
    }
    '/api/expense': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/expense').default>>>>
    }
    '/api/expenses': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/expenses.get').default>>>>
    }
    '/api/income': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/income').default>>>>
    }
    '/api/transactions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transactions.get').default>>>>
    }
    '/api/user/create': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/create').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}