= Vision: *Budget Buddies*
Til Guhlmann <til.guhlmann@stud.htw-dresden.de>; Enna Scheer <enna.scheer@stud.htw-dresden.de>; Emujin Uuganbayar <emujin.uuganbayar@stud.htw-dresden.de>; Erik Vogt <erik.vogt@stud.htw-dresden.de>; Justus Müller <justus.mueller@stud.htw-dresden.de>; Mark Schrader <mark.schrader@stud.htw-dresden.de>; Khanh Ly La <khanhly.la@stud.htw-dresden.de>;
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Der Zweck dieses Dokuments ist es, die wesentlichen Bedarfe und Funktionalitäten des Systems *Budget Buddies* überblicksartig zu beschreiben. Der Fokus liegt auf den Fähigkeiten, die von Stakeholdern und adressierten Nutzern benötigt werden, und der Begründung dieser Bedarfe. Die Details, wie das System *Budget Buddies* diese Bedarfe erfüllt, werden durch _User Stories_ im _Product Backlog_ sowie dem _UX-Konzept_ beschrieben.

=== Zweck
Der Zweck dieses Dokuments ist es, die wesentlichen Anforderungen an das System aus Sicht und mit den Begriffen der künftigen Anwender zu beschreiben.

=== Gültigkeitsbereich (Scope)
Dieses Visions-Dokument bezieht sich auf das System *Budget Buddies*, das von *Finanz Tracker AG* entwickelt wird. Das System wird es der Zielgruppe bzw. den *Studenten* erlauben, unsere Hauptfunktionen wie _Verwaltung und Erfassen der Einnahmen und Ausgaben, Erstellen individueller Budgets sowie das Anlegen von Sparkonten für spezifische Ziele_ zu nutzen, um damit bessere finanzielle Organisation zu erreichen, Budgetdisziplin fördern, Eigenverantwortung stärken.

=== Definitionen, Akronyme und Abkürzungen
//Verweis passend zum Belegabgabe-Template se1_belegabgabe_t00.adoc
Siehe <<#glossary, Glossar>>.
//Siehe <<./glossary.adoc#glossary, Glossar>>.

=== Referenzen
//hier externe Verweise zu anderen Dokumenten, Quellen, Standards etc. einfügen, sofern notwendig


== Positionierung

=== Fachliche Motivation
Die *Budget Buddies AG* ist ein junges Start-up, gegründet von sieben engagierten Bachelor-Student:innen im letzten Semester ihres Studiums. Aus eigener Erfahrung wissen sie: Viele Studierende kämpfen mit finanziellen Schwierigkeiten, unvorhergesehenen Ausgaben und mangelndem Überblick über ihre Finanzen.

Bestehende Lösungen auf dem Markt sind oft komplex und teuer. Für viele Studierende einfach nicht leistbar.

Genau hier setzt *Budget Buddy* an: Eine kostenlose, intuitive App, die speziell auf die Bedürfnisse junger Menschen zugeschnitten ist. Sie hilft dabei, Einnahmen und Ausgaben zu verwalten, Budgets zu erstellen und Sparziele zu erreichen – einfach, übersichtlich und völlig kostenlos.

Unser Ziel ist es, finanzielle Selbstbestimmung für alle zu ermöglichen – unabhängig vom Kontostand.

=== Produktvision
//Eine Produktvision beschreibt das Einsatzziel der Anwendung und sorgt für ein gemeinsames Ziel und Verständnis für alle Beteiligten im Projekt. Geben Sie in knapper Form übersichtsartig die Positionierung der angestrebten Lösung im Vergleich zu verfügbaren Alternativen dar. Das folgende Format kann dazu verwendet werden:


[cols="1,3"]
|===
| Für | Student*innen/Schüler*innen
| der / die | Management der persönlichen Finanzen
| ist das  | Budget Buddies
| eine  | FinTech, PFM 
| der / die | kostengünstig
|===


//Beispiel
//[cols="1,3"]
//|===
//| Für | Studierende der HTWD
//| die | zu wenig Zeit in der Mittagspause zum Essen haben
//| ist   | Flying Burger
//| ein  | Lieferdient für Burger
//| der  | per Drohne liefert
//| anders als | landgestützte Lieferdienste
//| kann unser Produkt |  durchs Fenster direkt in den Hörsaal liefern.
//|===

== Stakeholder Beschreibungen

=== Zusammenfassung der Stakeholder

[%header, cols="1,3,3"]
|===
| Name | Beschreibung | Verantwortlichkeiten


| Budget Buddies - Projektteam
| Kursteilnehmer:innen des Moduls SE1, auch Entwickler:innen genannt, die für dieses Projekt zugeteilt wurden und die Verantwortung für die Entwicklung des Systems übernehmen.
| Das Entwicklungsteam ist verantwortlich für die Entwicklung des Systems und sorgt dafür, dass das System den Anforderungen der Stakeholder entspricht, sowie für die Qualitätssicherung des Systems.

| Studierende
| Die Zielgruppe des Systems sind Studierende, die ihre Finanzen verwalten möchten.
| Die Studierenden sind die Hauptnutzer des Systems. Sie nutzen das System, um ihre Einnahmen und Ausgaben zu verfolgen, Budgets zu erstellen und Sparziele zu erreichen.
|===

Die Verfeinerung der Stakeholder, die das System benutzen, wird im UX-Konzept mittels Personas vorgenommen.


== Produktüberblick

=== Bedarfe und Hauptfunktionen
//Vermeiden Sie Angaben zum Entwurf. Nennen wesentliche Features (Produktmerkmale) auf allgemeiner Ebene. Fokussieren Sie sich auf die benötigten Fähigkeiten des Systems und warum (nicht wie!) diese realisiert werden sollen. Geben Sie die von den Stakeholdern vorgegebenen Prioritäten an.

[%header, cols="4,1,4,1"]
|===
| Bedarf | Priorität | Features / Funktionen | Geplantes Release
| xx | 10/10 | Eintragen von Finanzeinnahmen | xx
| xx | 10/10 | Eintragen von Finanzausgaben | xx
| xx | 10/10 | Kategorisierung von Einnahmen und Ausgaben | xx
| xx | 10/10 | Übersicht über aktuelle Finanzen | xx
| xx | 9/10 | Prognosen  | xx
| xx | 7/10 | Spar-challenges | xx
| xx | 6/10 | Automatisches Kopieren der wiederkehrenden Ausgaben ins neue Semester (Grundkonzept) | xx
| xx | 5/10 | Finanzdaten-Export | xx
| xx | 5/10 | Simples Layout | xx
| xx | 5/10 | Zweite Sprache (Englisch) | xx
| xx | 4/10 | Dark-Mode | xx
| xx | 4/10 | individuelle anpassbare Elemente (Farben, Graphen, Zeiträum) | xx
| xx | 3/10 | Modulares Layout (Entfernen von Modulen möglich) | xx


|===


=== Zusätzliche Produktanforderungen
//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
Hinweise:

. Führen Sie die wesentlichen anzuwendenden Standards, Hardware oder andere Plattformanforderungen, Leistungsanforderungen und Umgebungsanforderungen auf
. Definieren Sie grob die Qualitätsanforderungen für Leistung, Robustheit, Ausfalltoleranz, Benutzbarkeit und ähnliche Merkmale, die Qualitätsanforderungen an das geplante Produkt beschreiben.
. Notieren Sie alle Entwurfseinschränkungen, externe Einschränkungen, Annahmen oder andere Abhängigkeiten, die wenn Sie geändert werden, das Visions-Dokument beeinflussen. Ein Beispiel wäre die Annahme, dass ein bestimmtes Betriebssystem für die vom System erforderliche Hardware verfügbar ist. Ist das Betriebssystem nicht verfügbar, muss das Visions-Dokument angepasst werden.
. Definieren Sie alle Dokumentationsanforderugen, inkl. Benutzerhandbücher, Onlinehilfe, Installations-, Kennzeichnungs- und Auslieferungsanforderungen.
. Definieren Sie die Priorität für diese zusätzlichen Produktanforderungen. Ergänzen Sie, falls sinnvoll, Angaben zu Stabilität, Nutzen, Aufwand und Risiko für diese Anforderungen.

[%header, cols="4,1,1"]
|===
| Anforderung | Priorität | Geplantes Release
| Rechnungs -& Belegscanner | 4/10 | xx
| AI-basierter Finanzcoach | 3/10 | xx
| Offline-Funktionalität | 3/10 | xx
| 2-Faktor-Authentifizierung | 2/10 | xx
|===
