= Backlogs: {project-name}
Til Guhlmann <til.guhlmann@stud.htw-dresden.de>; Enna Scheer <enna.scheer@stud.htw-dresden.de>; Emujin Uuganbayar <emujin.uuganbayar@stud.htw-dresden.de>; Erik Vogt <erik.vogt@stud.htw-dresden.de>; Justus Müller <justus.mueller@stud.htw-dresden.de>; Mark Schrader <smark.schrader@stud.htw-dresden.de>; Khanh Ly La <khanhly.la@stud.htw-dresden.de>
{localdatetime} 
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Sprint Backlog
Im Sprint Backlog werden die Tasks in jeder Iteration aufgelistet mit ihrem zugeordnetem Sprint, deren Bearbeitungsstatus und die zuständige Person.

Hier finden sie unser Sprint Backlog: https://github.com/users/mark-schrader/projects/3/views/1

== Product Backlog
Im Product Backlog sind die User Stories dokuementiert mit ihren Tasks und dem aktuellen Bearbeitungsstatus. Die Task sind einer Iteration und einer zuständigen Person zugeteilt.

Hier finden sie unser Product Backlog: https://github.com/users/mark-schrader/projects/3/views/9

== Risk-Board
Im Risk-Board sind unsere potentiellen Risiken aufgelistet, die unser Projekt zum stocken bringen können. Die Risiken sind in gering, mittel und hpch eingestuft und ihrem aktuellen Bewertungstatus Neu, Analyse, Bewertung und Bewältigung. 

Hier finden sie unser Risk-Board: https://github.com/users/mark-schrader/projects/3/views/4